---
title: "ANALISI ESPLORATIVA 2"
output: html_notebook
---



```{r, include=FALSE}


#Load the library and set the environment
library(ggplot2)

setwd("~/Documents/universita/bayesian_statistics-Guglielmi/GLAUCOMA_PROJECT/src/")

load("../R_object/Glaucoma_data.RData")

attach(Gdata)

```




RNFL average using visit2 as time

```{r, fig.height=4, fig.width=8, message=FALSE, warning=FALSE}

## define base for the graphs and store in object 'p'
p <- ggplot(data = Gdata[!is.na(RNFL_average),], aes(x = visit2, y = RNFL_average,  color= factor(Patient) )  )

p + geom_line() + geom_point() +
     geom_smooth(method = lm, color="black")  
```

mean_RNFL_thickness using visit2 as time

```{r, fig.height=4, fig.width=8, message=FALSE, warning=FALSE}

## define base for the graphs and store in object 'p'
p <- ggplot(data = Gdata[!is.na(RNFL_average),], aes(x = visit2, y = mean_RNFL_thickness,  color= factor(Patient) )  )

p + geom_line() + geom_point() +
     geom_smooth(method = lm, color="black")  
```



IOP (intra-ocular pressure). From now on visit2 is used as time.

```{r, fig.height=4, fig.width=8, message=FALSE, warning=FALSE}

## define base for the graphs and store in object 'p'
p <- ggplot(data = Gdata[!is.na(RNFL_average),], aes(x = visit2, y = IOP,  color= factor(Patient) )  )

p + geom_line() + geom_point() +
     geom_smooth(method = lm, color="black")  
```


IOP vs RNFL. 

```{r, fig.height=4, fig.width=8, message=FALSE, warning=FALSE}

## define base for the graphs and store in object 'p'
p <- ggplot(data = Gdata[!is.na(RNFL_average),], aes(x = RNFL_average, y = IOP,  color= factor(Patient) )  )

p  + geom_point() 
```

