---
title: "Glaucoma Structural Progression"
author: "Davide Burba, Matteo Muffo"
date: "December 1, 2017"
output: 
  beamer_presentation:
    keep_tex: yes
    theme: Warsaw
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



```{r include=FALSE}

setwd("~/Documents/universita/bayesian_statistics-Guglielmi/GLAUCOMA_PROJECT/src/analisi_exp_markdown/")

##################################################################
####################### LOADING DATA  ############################
##################################################################


# Gdata=read.table("../../data/data.csv", header=T,fill=T,sep=",")
# 
# 
# attach(Gdata)
# 
# # BUILDING A TIME VARIABLE (MINIMUM AGE=0 for each patient)
# time= numeric(506)
# for (i in unique(Patient))
# {
#   tmp=Gdata[Patient==i,]
#   index=which(Patient==i)
#   minage=min(tmp$Age)
#   time[index]=tmp$Age-minage
# }
# 
# #adding time to Gdata
# Gdata=cbind(Gdata,time)
# Gdata$time
# 
# 
# length(Patient[Patient==0]) # c'è un' osservazione strana, probabile errore
# Gdata[ Patient==0,] # quasi tutto NA -> rimuoviamola per ora
# Gdata=Gdata[ Patient!=0,]
# 
# 
# #Save the data.frame
# save (Gdata, file="../../R_object/Glaucoma_data.RData")

load("../../R_object/Glaucoma_data.RData")

attach(Gdata)




dim(Gdata)
length(unique(Patient)) # 55 pazienti

```

## EXPLORATORY ANALYSIS
- Number of visits per patient


```{r echo=FALSE, fig.height=4, fig.width=14}
##################################################################
##################### DATA VISUALIZATION  ########################
##################################################################
                           
library(ggplot2)

# patient
ggplot(data= Gdata, aes(factor(Patient), fill=1) ) + 
  geom_bar()+
  theme(legend.position = "none", axis.text.x  = element_text(angle=90, hjust=1, vjust=0.9)) +
  geom_hline(yintercept = mean(mean(table(Patient))), color="red")

```

```{r include=FALSE}
#numero visite per paziente:
N=mean(table(Patient))
N
quantile(table(Patient),0.25)
quantile(table(Patient),0.5)
quantile(table(Patient),0.75)
```
- Mean number of observations: 9.2
- 0.25 quantile: 9
- 0.50 quantile: 11
- 0.75 quantile: 11


##

- female vs male

```{r echo=FALSE, fig.height=4, fig.width=4}

#female vs male
ggplot(data= Gdata, aes(Sex, fill=Sex  ) ) + 
  geom_bar()+
  theme(legend.position = "none", axis.text.x  = element_text(angle=0, hjust=1, vjust=0.9)) 
```

##
- type of glaucoma

```{r echo=FALSE , fig.height=4, fig.width=4}

# type of glaucoma
ggplot(data= Gdata, aes(Type_of_glaucoma, fill=Type_of_glaucoma  ) ) + 
  geom_bar()+
  theme(legend.position = "none", axis.text.x  = element_text(angle=0.45, hjust=1, vjust=0.9)) 

```

```{r eval=FALSE, include=FALSE}

### NOT SURE THOSE ARE IMPORTANT -> HIDDEN AT THIS MOMENT

# sup_10thpercent
ggplot(data= Gdata, aes( sup_10thpercent )  ) + 
  geom_histogram(col="white", 
                 fill="blue",
                 binwidth = 10) +
  ylab("relative frequencies") + 
  scale_y_continuous(labels=scales::percent) +
  geom_bar()+
  theme(legend.position = "none", axis.text.x  = element_text(angle=0, hjust=1, vjust=0.9)) 


# sup_25thpercent
ggplot(data= Gdata, aes( sup_25thpercent )  ) + 
  geom_histogram(col="white", 
                 fill="blue",
                 binwidth = 25) +
  ylab("relative frequencies") + 
  scale_y_continuous(labels=scales::percent) +
  geom_bar()+
  theme(legend.position = "none", axis.text.x  = element_text(angle=0, hjust=1, vjust=0.9)) 

# Periph
ggplot(data= Gdata, aes(factor(Periph), fill=factor(Periph) ) ) + 
  geom_bar()+
  theme(legend.position = "none", axis.text.x  = element_text(angle=0, hjust=1, vjust=0.9)) 

```




```{r include=FALSE, fig.height=2, fig.width=6}


###### Proviamo a "visualizzare" un unico paziente

Paz=590
Gdata_paz=Gdata[Patient==Paz,]
dim(Gdata_paz)

#qualche variabile: 
Gdata_paz$yearofglaucoma
Gdata_paz$Color
Gdata_paz$Periph
Gdata_paz$Visit
Gdata_paz$Progression
Gdata_paz$Progression1
Gdata_paz$ProgressionStructure1
Gdata_paz$ProgressionStructure
Gdata_paz
Gdata_paz$Age # variabile tempo!
Gdata_paz$age65
Gdata_paz$visualizationofON
Gdata_paz$MAP
Gdata_paz$FieldsComment
Gdata_paz$Field2
Gdata_paz$acuity





#MODIFICHE STRUTTURALI (riguardo al nervo ottico)
#RNFL
Gdata_paz$RNFL_average 
Gdata_paz$RNFL_cross_sectinal_area
Gdata_paz$RNFL_Multi_G_center
Gdata_paz$RNFL_Multi_Nasal
Gdata_paz$RNFL_Multi_Temp
Gdata_paz$RNFL_Multi_NI
Gdata_paz$RNFL_Multi_NS
Gdata_paz$RNFL_Multi_TI
Gdata_paz$RNFL_Multi_TS
Gdata_paz$RNFL_quad_Inf
Gdata_paz$RNFL_quad_nasal
Gdata_paz$RNFL_quad_Sup
Gdata_paz$RNFL_quad_temp
Gdata_paz$RNFL_thickness_superior
Gdata_paz$RNFL_thickness_inferior
Gdata_paz$RNFL_thickness_nasal
Gdata_paz$RNFL_thickness_temporal
Gdata_paz$OCT_RNFL_Signal_Strength
Gdata_paz$mean_RNFL_thickness
#RIM
Gdata_paz$Rim_area
Gdata_paz$RimArea
Gdata_paz$rim_volume



#MODIFICHE FUNZIONALI 
Gdata_paz$MD # Deviazione media CAMPO VISIVO!
Gdata_paz$PSD #Pattern Standard Deviation, nel perimetro Humphrey

```




## RNFL average


```{r echo=FALSE , fig.height=4, fig.width=8,  message=FALSE, warning=FALSE}


## define base for the graphs and store in object 'p'
p <- ggplot(data = Gdata[!is.na(RNFL_average),], aes(x = time, y = RNFL_average, group = Patient, color= factor(Patient) )  )

## just plotting points (a.k.a., scatterplot)
#p 

p + geom_line() + geom_point() +
     stat_smooth(aes(group = 1)) 


```


## RNFL average

- By Sex

```{r echo=FALSE , fig.height=2, fig.width=6 ,  message=FALSE, warning=FALSE}

p3 <- ggplot(data = Gdata[!is.na(RNFL_average) &!is.na(Sex),], aes(x = time, y = RNFL_average, group = Patient, color= factor(Patient) )  )

p3 + geom_line() + geom_point() +
     stat_smooth(aes(group = 1))  +
     stat_summary(aes(group = 1), fun.y = mean, shape = 17, size = 0.5) + facet_grid(. ~ Sex)

```


## RNFL average

- Only POAG Glaucoma

```{r echo=FALSE , fig.height=2, fig.width=6 ,  message=FALSE, warning=FALSE}


p4=ggplot(data = Gdata[Type_of_glaucoma=="POAG",], aes(x = time, y = RNFL_average, group = Patient, color= factor(Patient)))

p4 + geom_line() + geom_point() +
     stat_smooth(aes(group = 1))  +
     stat_summary(aes(group = 1), fun.y = mean, shape = 17, size = 0.5) 

```

## PROGRESSION


```{r echo=FALSE , fig.height=4, fig.width=8,  message=FALSE, warning=FALSE}


## define base for the graphs and store in object 'p'
p5 <- ggplot(data = Gdata[!is.na(ProgressionStructure),], aes(x = time, y = ProgressionStructure, group = Patient, color= factor(Patient) )  )

## just plotting points (a.k.a., scatterplot)
#p 

p5 + geom_line() + geom_point()

#fa cagare
```



##TODO: 
-   Plot e analisi esplorativa altre variabili
-   Riempire dati mancanti



 
 
 
 